#               Copyright Matthew Pulver 2018.
# Distributed under the Boost Software License, Version 1.0.
#      (See accompanying file LICENSE_1_0.txt or copy at
#           https://www.boost.org/LICENSE_1_0.txt)

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015 # 64-bit
      INSTALL_SCRIPT1: 'call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
      INSTALL_SCRIPT2: 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64'
      CL: /IC:\Libraries\boost_1_67_0 /EHsc

install:
  - "%INSTALL_SCRIPT1%"
  - "%INSTALL_SCRIPT2%"

build_script:
  - cl.exe /Iinclude test/test_autodiff.cpp

test_script:
  - test_autodiff

# Notes:
#
# * Adding /EHsc resolved both warnings:
#   * C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xlocale(319): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
#   * c:\libraries\boost_1_67_0\boost\test\impl\execution_monitor.ipp(277) : warning C4717: 'boost::detail::report_error': recursive on all control paths, function will cause runtime stack overflow
