#           Copyright Matthew Pulver 2018 - 2019.
# Distributed under the Boost Software License, Version 1.0.
#      (See accompanying file LICENSE_1_0.txt or copy at
#           https://www.boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

environment:
  global:
    # see: http://www.boost.org/build/doc/html/bbv2/overview/invocation.html#bbv2.overview.invocation.properties
    # to use the default for a given environment, comment it out; recommend you build debug and release however:
    # on Windows it is important to exercise all the possibilities, especially shared vs static, however most
    # libraries that care about this exercise it in their Jamfiles...
    # B2_ADDRESS_MODEL: address-model=64,32
    # B2_LINK: link=shared,static
    # B2_THREADING: threading=multi,single
    B2_VARIANT: variant=release,debug

  matrix:
    - FLAVOR: Visual Studio 2017 C++2a Strict
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64
      CXXFLAGS: cxxflags=-permissive-
      CXXSTD: latest # 2a

    - FLAVOR: Visual Studio 2017 C++17
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64
      CXXSTD: 17

    - FLAVOR: Visual Studio 2017 C++14 (Default)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64,32

    - FLAVOR: Visual Studio 2015 C++14 (Default)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-14.0
      B2_ADDRESS_MODEL: address-model=64,32

    - FLAVOR: Visual Studio 2010, 2012, 2013
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: msvc-10.0,msvc-11.0,msvc-12.0

    - FLAVOR: cygwin (32-bit)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ADDPATH: C:\cygwin\bin;
      B2_ADDRESS_MODEL: address-model=32
      CXXSTD: 11,14,17,20
      # https://github.com/boostorg/test/issues/144
      DEFINES: define=_POSIX_C_SOURCE=200112L
      THREADING: threadapi=pthread
      TOOLSET: gcc

    - FLAVOR: cygwin (64-bit)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ADDPATH: C:\cygwin64\bin;
      B2_ADDRESS_MODEL: address-model=64
      CXXSTD: 11,14,17,20
      # https://github.com/boostorg/test/issues/144
      DEFINES: define=_POSIX_C_SOURCE=200112L define=__USE_ISOC99
      THREADING: threadapi=pthread
      TOOLSET: gcc

    - FLAVOR: mingw32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: i686
      B2_ADDRESS_MODEL: address-model=32
      CXXSTD: 11,14,17,20
      SCRIPT: ci\appveyor\mingw.bat

    - FLAVOR: mingw64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86_64
      B2_ADDRESS_MODEL: address-model=64
      CXXSTD: 11,14,17,20
      DEFINES: define=__USE_ISOC99
      SCRIPT: ci\appveyor\mingw.bat

install:
  - set SELF=%APPVEYOR_PROJECT_NAME:-=autodiff
  - git clone https://github.com/boostorg/boost-ci.git C:\boost-ci
  - xcopy /s /e /q /i C:\boost-ci\ci .\ci
  - ci\appveyor\install.bat

build: off

test_script:
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master
  - set SELF=%APPVEYOR_PROJECT_NAME:-=autodiff
  - PATH=%ADDPATH%%PATH%
  # The definition of TOOLCXX omits CXXSTD= if it was not defined above
  - IF NOT DEFINED CXXSTD (SET TOOLCXX=toolset=%TOOLSET%) ELSE (SET TOOLCXX=toolset=%TOOLSET% cxxstd=%CXXSTD%)
  # Echo the complete build command to the build log
  - IF NOT DEFINED SCRIPT                         (ECHO b2 libs/%SELF:\=/% %TOOLCXX% %CXXFLAGS% %DEFINES% %THREADING% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3)
  # Now go build...
  - IF DEFINED SCRIPT (call libs\%SELF%\%SCRIPT%) ELSE (b2 libs/%SELF:\=/% %TOOLCXX% %CXXFLAGS% %DEFINES% %THREADING% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3)
