fixes:
  - home/travis/build/*/boost-root/boost/::include/boost/
  - home/travis/build/*/boost-root/libs/*/src/::include/

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no