#               Copyright Matthew Pulver 2018.
# Distributed under the Boost Software License, Version 1.0.
#      (See accompanying file LICENSE_1_0.txt or copy at
#           https://www.boost.org/LICENSE_1_0.txt)

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
#           - cppcheck # version 1.61 doesn't recognize if constexpr
            - libboost-dev
            - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COMPILER=clang++-5.0 && CXXSTD=c++17"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
#           - cppcheck # version 1.61 doesn't recognize if constexpr
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++17"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
#           - cppcheck # version 1.61 doesn't recognize if constexpr
            - boost1.67
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++11"
    - os: osx
      osx_image: xcode9.3
      env:
#       - MATRIX_EVAL="brew update && brew install gcc && brew install cppcheck && COMPILER=clang++ && CXXSTD=c++1z"
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++1z"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-cache search libboost

script:
  - $COMPILER --version
  - $COMPILER test/test_autodiff.cpp -std=$CXXSTD -Iinclude -Wall -o test_autodiff
  - ./test_autodiff
# - cppcheck --version
# - cppcheck --error-exitcode=1 -Iinclude example/
